### ISSUE TITLE
Admin : When title is changed it is not reflecting in page.

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/G-V-Roberts#15]
![3](https://cloud.githubusercontent.com/assets/13309806/9872348/4c36325a-5b45-11e5-9491-ae2f9420573a.png)

**Comment by roseliesromeo** [comment]
Hi Ganesh,

It's not advisable to have the changes in the page title reflect in the main navigation label and vice-versa, because there are instances where the main navigation labels are different from the page title. They should be taken individually. Currently, if I change the page title, the corresponding menu label will also change respectively.  Kindly revert the implementation.

Take for example below image:
![image](https://cloud.githubusercontent.com/assets/11186313/10360307/4a80a504-6dd2-11e5-951b-7a0390a48961.png)
